.eslintrc.json, package-lock.json, package.json
=> add eslint npm

routes/account.js, swagger-output.json
modify swagger-output doc
移除Dev API
=> modify swagger-output doc

example.env, utils/mailer.js
feat: update superhandy gmail
This pull request adds the following gmail setting
- update email template
- add a new environment variable
=> [feat] update superhandy gmail

utils/mailer.js
refactor: adjust an email account to environment
=> [refactor] adjust an email account to environment

controller/accountController.js, models/userModel.js, routes/account.js
1. modify userModel, set posterIntro and helperIntro default value.
2. modify response content of info-form route, both get and patch method
=> modify info-form的回傳內容

service/fakeExcellentHelpers.js
=> [docs] update fake data

controller/userController.js, models/userModel.js, routes/users.js, service/initTasks.js, service/initUsers.js, service/validator.js, swagger-output.json
- Add validation for forgot password. Originally, a token was used for validation, but it is not secure. This means that forgot password can only be used once, and if it needs to be used again, the user needs to go back to /forgot-password page.
- Add update password feature.
- Change to remove only default fake data (including User and Task).
- Change the validation for forgot password to require a password length of at least 8 characters.
=> S02 + S03 密碼相關 About Password

routes/account.js
fix swagger security as Bearer
=> fix swagger security as Bearer

controller/accountController.js, models/userModel.js, routes/account.js, swagger-defintion.js, swagger-output.json
- Get the current balance of Super Coins and Helper Coins
=> Feature：A01 ＋ A02 + A03 + A04 我的帳號 My Account

connections/index.js, controller/accountController.js, controller/taskController.js, db/initCategories.js, db/initTasks.js, models/taskModel.js, routes/account.js, routes/postTask.js, service/exposurePlan.js, service/taskValidator.js, service/validatorMoney.js, swagger-defintion.js, swagger-output.json
- 將草稿、發佈獨立 api 功能
- 調整發佈兩種功能，編輯、上架、下架
- 新增金流檢查
- 新增寫入交易資訊
=> Feat：調整刊登任務

controller/taskController.js, controller/tasksManageController.js, models/taskModel.js, routes/index.js, routes/tasksManage.js, swagger-defintion.js, swagger-output.json
- Get all posted tasks history records
- Get all applied tasks history records
- Get task details
=> Feat：任務管理(列出發案歷史紀錄、列出接案歷史紀錄、取得任務詳情)

swagger-defintion.js, swagger-output.json
=> Docs：add notifyId to swagger

controller/accountController.js, controller/homeController.js, controller/notifyController.js, controller/taskController.js, controller/tasksManageController.js, db/initNotify.js, models/notifyModel.js, models/taskModel.js, routes/tasksManage.js, swagger-defintion.js, swagger-output.json
- 列出接案歷史紀錄：任務管理的狀態對應
- 取得任務詳情：當找不到任務編號時回覆錯誤
- 調整 prettier
- 調整通知已讀狀態為未讀
=> Refactor：任務管理的狀態對應、調整 style

controller/homeController.js, controller/taskController.js, service/taskValidator.js, swagger-defintion.js, swagger-output.json
- 取得已完成之案例的 landmark 移除，由 address 替代
- 發佈草稿的 status type publish -> published
- 編輯下架任務，不可以更改 tilte
- 儲存草稿必要欄位為 title，調整 contactInfo 裡面的欄位，有這些資訊再檢查
- 更新 swagger docs
=> Refactor：與前端討論後建議修改項目(首頁+刊登)

controller/findTaskController.js, routes/findTask.js, routes/index.js, swagger-output.json
[feat] 新增 find-task/apply/:taskId 幫手應徵功能
[fix] findTaskDetails查無對應user帳號時，報錯40200
=> [feat] 新增 find-task/apply/:taskId 幫手應徵功能

controller/findTaskController.js
=> [fix] "sortBy" typo

controller/findTaskController.js
- mongoose不支援helpers.length這種使用方式
=> [fix] mongoose不支援helpers.length這種使用方式

controller/findTaskController.js, routes/findTask.js, swagger-output.json
1. 有填寫縣市地區時，僅顯示該區任務(不使用半徑參數)。
2. 使用經緯度時，顯示該半徑內任務(半徑介於0~10公里，不包含0)。
3. 參數同時給予縣市地區&經緯度，則會執行規則1
=> [feat] 調整find-task/map邏輯

controller/tasksManageController.js, models/taskModel.js
- 成功媒合時，task要紀錄currentHelperId。
便於後續查詢資料能夠快速找到幫手資訊
=> [feat] 成功媒合時，task要紀錄currentHelperId

bin/www, controller/chatController.js, controller/tasksManageController.js, models/chatModel.js, models/taskModel.js, package-lock.json, package.json, routes/chat.js, routes/index.js, service/socket-io.js, swagger-defintion.js, swagger-output.json
- API新增chat/list: 取得該用戶的所有聊天室清單
- API新增chat/history: 取得指定聊天室的歷史訊息
- 新增chatModel
- 新增socket-io.js: 處理websocket相關的連線
=> [feat] 新增websocket

connections/index.js, db/initChats.js, db/initTasks.js
=> [feat] 新增initChats 初始化聊天紀錄

controller/accountController.js, controller/linepayController.js, routes/index.js, routes/linepay.js, swagger-defintion.js, swagger-output.json
- 調整 linepay 交易機制，由前端打後端再跟 linepay 確認
- 修正 linepay 交易
- 移除不需要的 api
- 查詢點數交易紀錄，必須篩選出已經完成交易的 linepay
=> [fix] linepay save money

controller/chatController.js, controller/tasksManageController.js, routes/chat.js, swagger-defintion.js, swagger-output.json, utils/websocket.js
- fix : Swagger chat/list 多了一個後括號
- feat: 調整chat/list回傳內容，新增title、selfRole、partnerRole
- feat: 新增emitCreateNewChat，當任務媒合成功時，幫案主與幫手開啟聊天室
=> [feat] 新增 任務媒合成功，通知在線的雙方並創建chatRoom。 修改chat/list格式

controller/accountController.js, routes/account.js, swagger-output.json
-  patch account/info-form 增加可編輯的欄位avatarPath
=> [feat] patch account/info-form 增加可編輯的欄位avatarPath

controller/accountController.js
=> Fix：userTrans is not displayed normally

controller/findTaskController.js, db/initTasks.js
- find-task/list與map，自動將"台"轉成"臺"再做比較，避免用戶新增了task卻查詢不到
=> [feat] find-task/list與map，自動將"台"轉成"臺"再做比較

controller/findTaskController.js
- fix bug: find-task/map在沒有輸入地址的情況下，後端對地址做了replace與驗證，導致錯誤
=> [fix] find-task/map 地址的驗證導致500

controller/accountController.js, controller/taskController.js, controller/tasksManageController.js, db/initNotify.js, db/initPlans.js, db/initTasks.js, models/planModel.js, routes/account.js, routes/tasksManage.js, service/statusMapping.js, swagger-defintion.js, swagger-output.json
- bug：刪除任務後的退款，只能退薪水
- bug：前端發佈任務時，後端需要依照曝光方案來決定是否給予urgent tag
- feat：後端點數歷史API，需要提供task title
- feat：平台費採無條件捨去
- chore：移除不需要的通知
- feat：新增關鍵字搜尋任務
- chore：調整假資料
- refactor：曝光方案資訊整合到 planModel.js
=> Fix：測試後修改有問題的地方

controller/findTaskController.js
- findTask/map 改回原本的邏輯，有地址就用地址優先
=> [feat] findTask/map 改回原本的邏輯，有地址就用地址優先

controller/findTaskController.js
- fix findTask/detail關聯幫手的欄位對應錯誤
=> [fix] findTask/detail關聯幫手的欄位對應錯誤

controller/findTaskController.js
- findTask/detail幫手查看已接過的任務詳情時，無法正確顯示relation
=> [fix] findTask/detail幫手查看時，無法正確顯示relation

connections/index.js
- 只有在環境變數設定成'initDB'的情況下才會重置DB
=> [feat] 只有在環境變數設定成initDB的情況下才會重置DB

controller/tasksManageController.js, routes/index.js, routes/tasksScheduler.js, swagger-output.json, swagger.js
=> Feat：過期排程 api

controller/tasksManageController.js
=> refactor : remove deletedAt 

controller/findTaskController.js, controller/tasksManageController.js
- 找任務計算完成率，新增 cofirmed 
- getPostedTasksHistQuery 新增 statusReason
=> Feat：調整商業邏輯

service/taskValidator.js
- 刊登任務時，圖片只能五張上傳
- 刊登任務時，阻擋使用者輸入不正常的符號等等
=> [feat] Add more validation
